### ISSUE TITLE
Validate inputs

### ISSUE THREAD

**Issue by simenandre** [cobraz/setup-inputs#4]
I imagine it could be useful to validate along with the parsing.

Maybe our configuration could look something like this:

```yaml
- uses: cobraz/setup-inputs@v1
  with:
    inputs: |
      tag:
        required: true
      service:
        required: true
      env:
        required: true
```

Right now, the action naively just takes and returns the inputs. With some inputs, we can ensure the inputs are there and exit early 👍
